𝐀 𝐧𝐨𝐭𝐞𝐛𝐨𝐨𝐤 𝐭𝐨 𝐡𝐞𝐥𝐩 𝐞𝐯𝐞𝐫𝐲𝐨𝐧𝐞 𝐟𝐚𝐦𝐢𝐥𝐢𝐚𝐫𝐢𝐳𝐞 𝐭𝐡𝐞𝐦𝐬𝐞𝐥𝐯𝐞𝐬 𝐰𝐢𝐭𝐡 𝐭𝐡𝐞 𝐍𝐮𝐦𝐩𝐲 𝐥𝐢𝐛𝐫𝐚𝐫𝐲 𝐚𝐧𝐝 𝐢𝐭𝐬 𝐤𝐞𝐲 𝐟𝐞𝐚𝐭𝐮𝐫𝐞𝐬 𝐟𝐨𝐫 𝐛𝐞𝐠𝐢𝐧𝐧𝐞𝐫𝐬 𝐨𝐫 𝐥𝐚𝐬𝐭-𝐦𝐢𝐧𝐮𝐭𝐞 𝐫𝐞𝐯𝐢𝐞𝐰

NUMPY: 
It is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [22]:
import numpy as np
np.__version__

'1.26.4'

Creating an Array [1D]

In [23]:
arr= np.array([25,10,20,30,40,50,60])  #creating and dispalying an 1D array
arr

array([25, 10, 20, 30, 40, 50, 60])

In [24]:
ls=[25,10,20,30,40,50,60]      #converting list into array
arr=np.array(ls)
arr

array([25, 10, 20, 30, 40, 50, 60])

In [25]:
print(arr)

[25 10 20 30 40 50 60]


In [26]:
type(ls)

list

In [27]:
type(arr)

numpy.ndarray

𝐁𝐚𝐬𝐢𝐜 𝐅𝐮𝐧𝐜𝐭𝐢𝐨𝐧𝐬 𝐢𝐧 𝐍𝐮𝐦𝐩𝐲

In [28]:
arr+5  #added 3 to every element of the array

array([30, 15, 25, 35, 45, 55, 65])

In [29]:
arr/5

array([ 5.,  2.,  4.,  6.,  8., 10., 12.])

In [30]:
max(arr)   #max() function retunrs the maximum element3

60

In [31]:
min(arr)

10

In [32]:
np.sort(arr)

array([10, 20, 25, 30, 40, 50, 60])

In [33]:
sum(arr)   #sort() function sorts the array elements by default in ascending order

235

In [34]:
df = np.array([10, 20, 25, 30, 40, 50, 60])
print(df)


[10 20 25 30 40 50 60]


In [35]:
sum(df)    #returns the sum of all elements in the array

235

In [36]:
np.mean(df)   #returns the avg/mean of array elements

33.57142857142857

In [37]:
np.median(arr)     #returns the median(mid element) in the array

30.0

Numpy has no MODE Function

In [38]:
np.mode(df)

AttributeError: module 'numpy' has no attribute 'mode'

In [ ]:
np.std(df)   #returns standard deviation

16.19397721250662

In [ ]:
df.ndim  #returns dimension of array

1

In [ ]:
df.size   #or     len(arr)        #tells the size of t

7

In [ ]:
df.shape   #returns a tuple indicating dimension of an

(7,)

In [ ]:
df.dtype  #returns data type of array(type of elements st

dtype('int32')

In [ ]:
array=np.array([25,10,20,30,'Hello'])
array

array(['25', '10', '20', '30', 'Hello'], dtype='<U11')

In [ ]:
array.dtype

dtype('<U11')

𝐒𝐥𝐢𝐜𝐢𝐧𝐠/𝐈𝐧𝐝𝐞𝐱𝐢𝐧𝐠 𝐢𝐧 𝟏𝐃 𝐀𝐫𝐫𝐚𝐲

In [ ]:
pd= np.array([25,10,20,40,50,60])
pd[-3::1]   #or arr[-3:]      #last 1 is known as jump point and shows we have to move in forward direction and if it is negative then it shows that we have to move in backward direction


array([40, 50, 60])

𝐑𝐚𝐧𝐝𝐨𝐦 𝐌𝐨𝐝𝐮𝐥𝐞

In [ ]:
import random
random.randint(1,20)        #generate a number randomly between 1 and 20
#The output of this will be different everytime we run it cause

4

In [ ]:
arr=np.random.randint(1,12,5)        #it means generate 5 numbers randomly between 1 and 10
arr

array([ 6,  1,  9, 10,  2])

In [ ]:
arr=np.random.randint(1,12,5)
arr.dtype

dtype('int32')

In [ ]:
arr=np.random.randint(1,12,5,dtype='int64')     #In the above case , the data type was coming out to be INT32 but here we have specified what data type we want accoring to our choice 
arr.dtype

dtype('int64')

In [ ]:
#30th July
import numpy as np
arr=np.random.randint(1,20,30)        #it means generate 30 numbers randomly between 1 and 20
arr

array([15, 16, 19, 10,  4, 15, 15, 10,  4,  9,  7,  3,  5, 18,  5, 13, 12,
        9,  4,  3,  6, 12,  6,  2, 11, 19, 16, 17, 13,  3])

In [ ]:
arr<10     #returns TRUE where the condition is met and reurns FALSE wher if it is not met

array([False, False, False, False,  True, False, False, False,  True,
        True,  True,  True,  True, False,  True, False, False,  True,
        True,  True,  True, False,  True,  True, False, False, False,
       False, False,  True])

ALTERNATE METHOD

In [ ]:
def lessthan10():               
    numbers=arr[arr<10]
    print(numbers)

lessthan10()

[4 4 9 7 3 5 5 9 4 3 6 6 2 3]


In [ ]:
len(arr[arr<12])        #returns the no. of elements less than 10


17

𝐒𝐭𝐫𝐢𝐧𝐠 𝐌𝐨𝐝𝐮𝐥𝐞

In [ ]:
import string
string.digits

'0123456789'

In [ ]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

𝟐𝐃 𝐀𝐫𝐫𝐚𝐲

In [ ]:
ls=[[1,2,3],[4,5,6],[7,8,9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
type(ls)

list

In [ ]:
arr2=np.array(ls)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(3, 3)

S𝐥i𝐜i𝐧g/I𝐧d𝐞x𝐢n𝐠 𝐢n 2𝐃 𝐀r𝐫a𝐲

In [ ]:
arr2[2]

array([7, 8, 9])

In [ ]:
arr2[-2]

array([4, 5, 6])

In [ ]:
arr2[0:2] #it will print the values of matrix from index zero to one and exclude to print the index value of 2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2[0:2,1:3] #first value print the rows and second value print the column value

array([[2, 3],
       [5, 6]])

In [ ]:
arr2[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
arr2[0:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

 𝟑𝐃𝐀𝐫𝐫𝐚𝐲

In [ ]:
ls1=[[[1,2],[3,4]],
     [[5,6],[7,8]],
     [[9,10],[11,12]]]
ls1

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

In [ ]:
arr3=np.array(ls1)
arr3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
arr3.ndim

3

In [ ]:
arr3.dtype

dtype('int32')

In [ ]:
arr3.shape      #table,row,column       
#It indicates that this arr3 array has 3 (2-D) arrays that have a shape of 2*2 which means

(3, 2, 2)

In [ ]:
arr3[:,0,:]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
ls2=[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
arr4=np.array(ls2)
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

 
𝐒𝐥𝐢𝐜𝐢𝐧𝐠/𝐈𝐧𝐝𝐞𝐱𝐢𝐧𝐠 𝐢𝐧 𝟑𝐃 𝐀𝐫𝐫𝐚𝐲

In [ ]:
arr4[:,1:,1:]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [ ]:
arr4[:,-1,::-1]

array([[9, 8, 7],
       [9, 8, 7],
       [9, 8, 7],
       [9, 8, 7]])

 
𝐀𝐝𝐯𝐚𝐧𝐜𝐞𝐝 𝐅𝐮𝐧𝐜𝐭𝐢𝐨𝐧𝐬 𝐢𝐧 𝐍𝐮𝐦𝐩𝐲

RAVEL()

In [ ]:

arr3.ravel()        #or flatten() function      #used to change a 2-dimensional array or a multi-dimensional array into a contiguous flattened array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

RESHAPE()

In [39]:
# Define arr3
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr3.reshape(12,)   #shape=(3,2,2) = 3*2*2=12       #gives a new shape to an array without changing its data.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
reshaped_arr3 = arr3.reshape(3, 2, 2)

print(reshaped_arr3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


ARGMIN()

In [41]:
l=[5,2,8,6,1,9,3]
a=np.array(l)
a
np.argmin(a,axis=0)    #numpy.argmin(array, axis = None, out = None)

4

ARGMAX()

In [42]:
np.argmax(a,axis=0)   #returns index of the max element of the array)

5

ARGSORT()

In [43]:
np.argsort(a)       #numpy.argsort(arr, axis=-1, kind=’quicksort’, order=None)=returns an array of indices of value arranged in ascending order

array([4, 1, 6, 0, 3, 2, 5], dtype=int64)

ONES()

In [44]:
np.ones(10)   #returns a new array of given shape and type, with ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

ZEROS()

In [46]:
np.zeros(5)   #returns a new array of given shape and type,  with zeros)

array([0., 0., 0., 0., 0.])

LINSPACE()

In [47]:
np.linspace(1,20,10)  #returns uniform distribution of 10 numbers between 1 and 20

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

POWER()

In [48]:
array1 = [2, 2, 2, 2, 2] 
array2 = [2, 3, 4, 5, 6]
out=np.power(array1,array2)     #array element from first array is raised to the power of element from second array
out

array([ 4,  8, 16, 32, 64])

SIGN()

In [49]:
ar1=[1,4,0,-3,0,-6]
ar2=np.sign(ar1)        #indicates the sign of a number element-wise. For integer inputs, if array value is greater than 0 it returns 1, if array value is less than 0 it returns -1, and if array value 0 it returns 0.
ar2

array([ 1,  1,  0, -1,  0, -1])

RECIPROCAL()

In [50]:
a=[0.5,1,0.25,0.2]
r=np.reciprocal(a)      #returns the reciprocal of array elements
r

array([2., 1., 4., 5.])

RESIZE())

In [51]:
gfg = np.array([1, 2, 3, 4, 5, 6])
gfg.resize(2,3)                     #resizes the array into our desired shape
gfg                                 #Here, converted a 1D array into 2D array of 2 rows and 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

SAVETXT()

In [52]:
array1 = np.array([[1, 3, 5], 
                   [7, 9, 11]])
np.savetxt('file1.txt', array1)        #save an array to a text file

LOADTXT()

In [53]:
loaded_array = np.loadtxt('file1.txt')      #load the saved txt file
print(loaded_array)

[[ 1.  3.  5.]
 [ 7.  9. 11.]]


𝐒𝐎𝐌𝐄 𝐏𝐑𝐀𝐂𝐓𝐈𝐂𝐄 𝐏𝐑𝐎𝐆𝐑𝐀𝐌

In [54]:
#Problem 1. Given a 1D Numpy array, replace all negative values with zero.
def replace(arr):
    arr[arr<0]=0
    return arr
arr=np.array([1,-2,3,5,-7,-9])
result=replace(arr)
print(result)

[1 0 3 5 0 0]


𝐖𝐇𝐄𝐑𝐄 𝐅𝐮𝐧𝐜𝐭𝐢𝐨𝐧 𝐢𝐧 𝐍𝐮𝐦𝐩𝐲

𝐒𝐲𝐧𝐭𝐚𝐱 : 𝐧𝐮𝐦𝐩𝐲.𝐰𝐡𝐞𝐫𝐞(𝐜𝐨𝐧𝐝𝐢𝐭𝐢𝐨𝐧[, 𝐱, 𝐲])

𝐜𝐨𝐧𝐝𝐢𝐭𝐢𝐨𝐧 : 𝐖𝐡𝐞𝐧 𝐓𝐫𝐮𝐞, 𝐲𝐢𝐞𝐥𝐝 𝐱, 𝐨𝐭𝐡𝐞𝐫𝐰𝐢𝐬𝐞 𝐲𝐢𝐞𝐥𝐝 𝐲.


In [55]:
#Problem 2. Given a 1D Numpy array , return a new array where if element is greater than 5 then square it and if less thaan 5 then return 0.
def pract(arr):
    result=np.where(arr>=5,arr**2,0)
    return result
arr=np.array([1,3,5,6,8,2,9,4])
result=pract(arr)
print(result)

[ 0  0 25 36 64  0 81  0]


In [56]:
#Problem 3. Given a 2D Array , return sum of each row as a 1D Array.
def row_sum(data):
    return np.sum(data,axis=1)
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
r_sum=row_sum(data)
print(r_sum)

[ 6 15 24]


In [57]:
#Problem 4. Given a 2D Numpy Array, extract all even numbers
def even(arr):
    return arr[arr%2==0]
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
even_no=even(arr)
print(even_no)

[2 4 6 8]
